const config = require('./services/config');
const { getMyIpAddresses } = require('./services/get-my-ip-addresses');
const app = require('./app');

const header = `
 _ __ _ __  _ __   _____      __
| '__| '_ \\| '_ \\ / _ \\ \\ /\\ / /
| |  | |_) | | | | (_) \\ V  V /
|_|  | .__/|_| |_|\\___/ \\_/\\_/
     |_|         pre-alpha test

Your RPNow server is ready!

Data will be stored in ${config.dataDir}.
Be sure to back this up regularly!

${(process.platform === 'win32' || process.platform === 'darwin') ? (
`To access RPNow on the local network, (i.e., when connected to the
same wi-fi as this computer) try visiting one of the following in your
web browser:`
):(
`To access this RPNow server, try visiting one of the following in your
web browser:`
)}

${(getMyIpAddresses().length > 0) ? (
getMyIpAddresses().map(ip => `* http://${ip}:${config.port}`)
):(
`  (Unable to determine my address.)`
)}

Have fun!
`;

app.listen(config.port, (err) => {
    if (err) {
        console.error(`RPNow failed to start: ${err}`);
        return;
    }

    // delay logging this until messages generated by vue-pronto are done
    setTimeout(() => console.log(header), 2000);
});
